import { ESTATE_TEMPLATE, IPS_TEMPLATE, RTQ_TEMPLATE } from "./contracts"

/* ------------------------------------------------------------------ */
/*  Shared rules applied to every extraction prompt                   */
/* ------------------------------------------------------------------ */

const COMMON_RULES = [
  "Return ONLY valid JSON. No markdown fences, no commentary, no trailing commas.",
  "Preserve the exact key names and nesting shown in the target JSON template.",
  "Do NOT invent facts that are not explicitly stated in the source document.",
  "If a value is missing or unclear, keep the template default instead of guessing.",
  "Normalize ALL monetary values to plain numbers: \"$1,200,000\" -> 1200000, \"$350,000\" -> 350000. Never keep $ signs, commas, or quotes around numbers.",
  "Keep arrays present even when empty.",
  "For percentage values in allocation tables, convert \"55.0%\" -> 55 (plain number).",
]

/* ------------------------------------------------------------------ */
/*  System prompt (shared across all doc types)                       */
/* ------------------------------------------------------------------ */

export function extractionSystemPrompt(documentLabel: string) {
  return [
    `You are a precision data-extraction engine for Penobscot Financial Advisors / TIAA Wealth Management documents.`,
    `You are extracting structured data from a ${documentLabel}.`,
    `These PDFs always follow the exact same template layout. Use the section numbers and table structures described in the user prompt to locate every value.`,
    "",
    ...COMMON_RULES,
  ].join("\n")
}

/* ================================================================== */
/*  IPS — Investment Policy Statement                                 */
/*  Penobscot Financial Advisors template (7 pages, 12 sections)      */
/* ================================================================== */

export function ipsExtractionPrompt(clientName: string) {
  return [
    `Extract the ${clientName} Investment Policy Statement into the JSON template below.`,
    "",
    "=== DOCUMENT STRUCTURE (every IPS follows this exact layout) ===",
    "",
    "SECTION 3a — The Portfolio (page 3)",
    "  Contains a table with columns: Account | Account Type | Approximate Value",
    "  Each row is one managed account. The last row is a TOTAL row.",
    "  -> Map each row (except TOTAL) into clientProfile.accounts[].",
    "     accountName  = the Account column text (e.g. \"John Smith - TIAA Traditional 403(b)\")",
    "     accountType  = the Account Type column text (e.g. \"Tax-Deferred\", \"Tax-Free\", \"Taxable\")",
    "     approximateValue = dollar amount as a plain number (\"$1,200,000\" -> 1200000)",
    "     institution  = infer from the account name: \"TIAA\" if the name mentions TIAA, \"Vanguard\" if it mentions Vanguard, otherwise the custodian name",
    "     beneficiaryStatus = leave as empty string (IPS does not contain beneficiary info)",
    "  -> clientProfile.totalPortfolioValue = the TOTAL row dollar amount as a plain number",
    "",
    "SECTION 3b — Investment Objectives (page 4)",
    "  A bulleted list of checked objectives (e.g. Capital Preservation, Income Generation, Growth and Income, Inflation Protection, Estate Planning / Legacy).",
    "  -> Map into investmentObjectives[] as an array of strings. Include ONLY the items that appear checked/selected (bold or with a filled square marker).",
    "",
    "SECTION 3c — Risk Tolerance (page 4)",
    "  A single-select list: Conservative | Moderately Conservative | Moderate | Moderately Aggressive | Aggressive.",
    "  One item is selected (bold or filled marker).",
    "  -> riskTolerance = the selected text exactly (e.g. \"Moderate\")",
    "",
    "SECTION 3d — Time Horizon (page 4)",
    "  A single-select list: 0-1 Year | 1-5 Years | 5-10 Years | 10-20 Years | 20+ Years.",
    "  -> timeHorizon = the selected text (e.g. \"10 - 20 Years\")",
    "",
    "SECTION 3e — Liquidity Needs (page 4)",
    "  A free-text paragraph describing retirement timeline, RMD plans, distribution amounts, and emergency reserve.",
    "  -> liquidityNeeds = the full paragraph text",
    "",
    "SECTION 5 — Return (page 5)",
    "  Contains the return goal as a prose paragraph. Look for a phrase like \"annualized net return of X-Y%\".",
    "  -> returnGoal = the full paragraph text from Section 5",
    "",
    "SECTION 6 — Asset Allocation (page 5)",
    "  Contains a header banner: \"Overall Target Asset Allocation: <Profile>\" (e.g. \"Moderate\")",
    "  -> targetAssetAllocation.portfolioProfile = the profile label (e.g. \"Moderate\")",
    "",
    "  Followed by a 4-row table with columns: Asset Class | Target Allocation | Allowable Range",
    "  The rows are ALWAYS in this order:",
    "    Row 1: Equity        (e.g. 55.0%, 45%-65%)",
    "    Row 2: Fixed Income   (e.g. 35.0%, 25%-45%)",
    "    Row 3: Real Assets OR Alternatives (e.g. 8.0%, 3%-12%)",
    "    Row 4: Cash & Equivalents (e.g. 2.0%, 0%-5%)",
    "  -> targetAssetAllocation.allocations MUST have exactly 4 items in that order.",
    "     For each: assetClass = column 1 text, targetAllocation = percentage as number (55.0% -> 55),",
    "     allowableMin = lower bound as number (45% -> 45), allowableMax = upper bound as number (65% -> 65).",
    "  IMPORTANT: If the document says \"Real Assets\", use \"Real Assets\" as the assetClass for row 3. If it says \"Alternatives\", use \"Alternatives\".",
    "",
    "SECTION 8 — Performance Evaluation and Reporting (page 6)",
    "  Contains a table with columns: Asset Class | Benchmark",
    "  Typical rows: Fixed Income, Equities, Real Assets.",
    "  -> benchmarks[] = one object per row: { assetClass: \"...\", benchmark: \"...\" }",
    "",
    "SECTION 11 — Advisor Notes (page 6)",
    "  Contains multiple titled paragraphs (bold title followed by colon, then text).",
    "  Common titles: Retirement Timeline, Pension Income, Tax-Loss Harvesting Opportunity, RMD Planning.",
    "  -> advisorNotes[] = one object per paragraph: { title: \"Retirement Timeline\", content: \"full text after the colon\" }",
    "",
    "currentHoldings: The IPS does NOT contain individual security-level holdings. Leave currentHoldings.accounts as an empty array. Set currentHoldings.asOf to empty string.",
    "",
    "=== EXAMPLE OUTPUT (for John Smith) ===",
    JSON.stringify(
      {
        clientProfile: {
          clientName: "John Smith",
          accounts: [
            { accountName: "John Smith - TIAA Traditional 403(b)", accountType: "Tax-Deferred", approximateValue: 1200000, institution: "TIAA", beneficiaryStatus: "" },
            { accountName: "John Smith - TIAA Roth 403(b)", accountType: "Tax-Free", approximateValue: 350000, institution: "TIAA", beneficiaryStatus: "" },
            { accountName: "John & Sarah Smith Joint Brokerage", accountType: "Taxable", approximateValue: 650000, institution: "Vanguard", beneficiaryStatus: "" },
            { accountName: "John Smith - Vanguard Rollover IRA", accountType: "Tax-Deferred", approximateValue: 300000, institution: "Vanguard", beneficiaryStatus: "" },
          ],
          totalPortfolioValue: 2500000,
        },
        investmentObjectives: ["Capital Preservation", "Income Generation", "Growth and Income", "Inflation Protection", "Estate Planning / Legacy"],
        riskTolerance: "Moderate",
        timeHorizon: "10 - 20 Years",
        returnGoal: "The portfolio targets an annualized net return of 5-7% over a full market cycle...",
        targetAssetAllocation: {
          portfolioProfile: "Moderate",
          allocations: [
            { assetClass: "Equity", targetAllocation: 55, allowableMin: 45, allowableMax: 65 },
            { assetClass: "Fixed Income", targetAllocation: 35, allowableMin: 25, allowableMax: 45 },
            { assetClass: "Real Assets", targetAllocation: 8, allowableMin: 3, allowableMax: 12 },
            { assetClass: "Cash & Equivalents", targetAllocation: 2, allowableMin: 0, allowableMax: 5 },
          ],
        },
        benchmarks: [
          { assetClass: "Fixed Income", benchmark: "Bloomberg U.S. Aggregate Bond Index" },
          { assetClass: "Equities", benchmark: "60% S&P 500 / 40% MSCI ACWI ex-US" },
          { assetClass: "Real Assets", benchmark: "Bloomberg Commodity Index" },
        ],
        advisorNotes: [
          { title: "Retirement Timeline", content: "John plans to retire at age 65 (in 3 years)..." },
          { title: "Pension Income", content: "John will receive $45,000/year from his university pension..." },
        ],
      },
      null,
      2,
    ),
    "",
    "(The example above is illustrative. Extract the actual values from the PDF.)",
    "",
    "Target JSON template (fill every field):",
    JSON.stringify(IPS_TEMPLATE, null, 2),
  ].join("\n")
}

/* ================================================================== */
/*  RTQ — Risk Tolerance Questionnaire                                */
/*  TIAA Wealth Management template (4 pages, 8 questions + scoring)  */
/* ================================================================== */

export function rtqExtractionPrompt(clientName: string) {
  return [
    `Extract the ${clientName} Risk Tolerance Questionnaire into the JSON template below.`,
    "",
    "=== DOCUMENT STRUCTURE (every RTQ follows this exact layout) ===",
    "",
    "PAGE 1 — Header & Financial Profile",
    "  Title: \"TIAA Institutional Risk Tolerance Assessment — <client name>\"",
    "  -> client.name = the client name, client.document = \"TIAA Institutional Risk Tolerance Assessment\"",
    "",
    "  \"WHAT ARE THE CLIENT'S TOTAL ASSETS?\" section (page 1, first blue banner):",
    "  Below the checklist, there is a bold summary line:",
    "    \"Assets Under Consideration: $X | Pension Income: $X/year (combined) | Social Security: $X/year (estimated, age Y)\"",
    "  -> financialProfile.assetsUnderConsideration = the dollar amount as number (e.g. 2500000)",
    "  -> financialProfile.pensionIncome.annualAmount = the pension dollar amount as number (e.g. 77000)",
    "  -> financialProfile.pensionIncome.source = \"Combined\" (or as specified)",
    "  -> financialProfile.pensionIncome.note = any parenthetical note (e.g. \"combined\")",
    "  -> financialProfile.socialSecurity.estimatedAnnual = the SS dollar amount as number (e.g. 58000)",
    "  -> financialProfile.socialSecurity.claimAge = the age number (e.g. 67)",
    "  -> financialProfile.socialSecurity.note = any parenthetical note (e.g. \"estimated, age 67\")",
    "",
    "  For employer stock: Look for any mention. If none, leave defaults (company=\"\", approxValue=0).",
    "",
    "QUESTIONS — Exact mapping (8 questions across pages 1-3):",
    "",
    "  Q1: \"WHAT IS THE CLIENT'S TIME HORIZON?\" (page 1)",
    "    Options: 0-4 Years (3pts) | 5-10 Years (6pts) | 11-20 Years (9pts) | 20 Years+ (12pts)",
    "    -> investmentPreferences.timeHorizon.selected = the selected option text",
    "    -> investmentPreferences.timeHorizon.points = the point value from the Scoring Summary table (may differ from the option points due to advisor adjustment)",
    "    -> investmentPreferences.timeHorizon.note = the Note paragraph below the options if present",
    "",
    "  Q2: \"WHAT IS THE CLIENT'S PRIMARY INVESTMENT OBJECTIVE?\" (page 1)",
    "    Options: Income (3pts) | Growth & Income (6pts) | Growth (9pts)",
    "    -> investmentPreferences.primaryInvestmentObjective.selected = selected text",
    "    -> investmentPreferences.primaryInvestmentObjective.points = points from Scoring Summary",
    "",
    "  Q3: \"WHAT IS THE CLIENT'S ANNUAL SPENDING / WITHDRAWAL POLICY?\" (page 1)",
    "    Options: Low 0-2% (3pts) | Moderate 4-5% (6pts) | High 5-7% (9pts)",
    "    -> investmentPreferences.annualSpendingPolicy.selected = selected text",
    "    -> investmentPreferences.annualSpendingPolicy.points = points from Scoring Summary",
    "    -> investmentPreferences.annualSpendingPolicy.note = the Note paragraph if present",
    "",
    "  Q4: \"WHAT IS THE CLIENT'S AVERAGE ANNUAL RETURN EXPECTATION?\" (pages 1-2)",
    "    Options: 0-3% (3pts) | 3-5% (6pts) | 5-7% (9pts) | More than 7% (12pts)",
    "    -> investmentPreferences.returnExpectation.selected = selected text",
    "    -> investmentPreferences.returnExpectation.points = points from Scoring Summary",
    "",
    "  Q5: \"WHAT IS THE CLIENT'S OVERALL INVESTMENT APPROACH?\" (page 2)",
    "    Options: Stability (3pts) | Slightly increase/minimize loss (6pts) | Moderate fluctuations/avoid significant losses (9pts) | Meaningful growth/moderate-high risk (12pts) | Maximum returns/maximum risk (15pts)",
    "    -> investmentPreferences.investmentApproach.selected = selected text",
    "    -> investmentPreferences.investmentApproach.points = points from Scoring Summary",
    "",
    "  Q6: \"HOW WOULD THE CLIENT REACT TO A PORTFOLIO LOSING 15% OF ITS VALUE IN THE FIRST YEAR OF RETIREMENT?\" (page 3)",
    "    Options: Extremely concerned/liquidate (3pts) | Concerned/consider liquidating (6pts) | Stay the course/review allocation (9pts) | Not overly concerned (12pts)",
    "    -> investmentPreferences.reactionToLoss.scenario = \"Portfolio losing 15% in first year of retirement\"",
    "    -> investmentPreferences.reactionToLoss.selected = selected text",
    "    -> investmentPreferences.reactionToLoss.points = points from Scoring Summary",
    "",
    "  Q7: \"WHICH OF THE FOLLOWING EVENTS DOES THE CLIENT FEAR THE MOST?\" (page 3)",
    "    Options: 10% loss in 6 months (3pts) | 10% loss in 1 year (6pts) | Prolonged downturn/sequence risk (7pts) | Underperform benchmarks (9pts) | Missed opportunity (15pts)",
    "    -> investmentPreferences.mostFearedEvent.selected = selected text",
    "    -> investmentPreferences.mostFearedEvent.points = points from Scoring Summary",
    "",
    "  Q8: \"WHAT IS THE CLIENT'S OVERALL KNOWLEDGE OF INVESTMENTS?\" (page 3)",
    "    Options: None (3pts) | Low (6pts) | Moderate (9pts) | High (12pts)",
    "    -> investmentPreferences.investmentKnowledge.selected = selected text",
    "    -> investmentPreferences.investmentKnowledge.points = points from Scoring Summary",
    "",
    "SCORING SUMMARY TABLE (pages 3-4)",
    "  A table with columns: Question | Selected Response | Points",
    "  The last row: TOTAL SCORE = sum of all points.",
    "  CRITICAL: Use the points from THIS table (not the option parenthetical) because the advisor may have adjusted them.",
    "  -> riskAssessment.totalScore = the TOTAL SCORE number (e.g. 55)",
    "",
    "  Below the table: \"RESULT: <PROFILE>\" in large text, followed by \"Score: X Range: Y-Z\"",
    "  -> riskAssessment.riskProfile = the profile label (e.g. \"Moderate\")",
    "  -> riskAssessment.scoreRange = the range text (e.g. \"52-67\")",
    "  -> riskAssessment.description = the paragraph below the result that describes the portfolio objective",
    "",
    "SUGGESTED ASSET ALLOCATION (page 4)",
    "  A visual bar/row showing 4 percentages with labels:",
    "    X% Equity | Y% Fixed Income | Z% Alternatives / Real Assets | W% Cash & Equivalents",
    "  -> suggestedAssetAllocation.equity = X (number, e.g. 55)",
    "  -> suggestedAssetAllocation.fixedIncome = Y (e.g. 35)",
    "  -> suggestedAssetAllocation.alternatives = Z (e.g. 8)",
    "  -> suggestedAssetAllocation.realAssets = Z (same value — the doc labels it \"Alternatives / Real Assets\")",
    "  -> suggestedAssetAllocation.cash = W (e.g. 2)",
    "",
    "ADDITIONAL INVESTMENT CONSTRAINTS (page 3)",
    "  Look for \"No ESG preference\" or similar -> investmentConstraints.esgPreference = false",
    "  If ESG is noted as a preference -> investmentConstraints.esgPreference = true",
    "  -> investmentConstraints.notes[] = array of strings, one per bullet/paragraph in the constraints section",
    "",
    "=== EXAMPLE OUTPUT (for John Smith) ===",
    JSON.stringify(
      {
        client: { name: "John Smith", document: "TIAA Institutional Risk Tolerance Assessment" },
        financialProfile: {
          assetsUnderConsideration: 2500000,
          employerStock: { company: "", approxValue: 0, note: "" },
          pensionIncome: { source: "Combined", annualAmount: 77000, note: "combined" },
          socialSecurity: { estimatedAnnual: 58000, claimAge: 67, note: "estimated, age 67" },
        },
        investmentPreferences: {
          timeHorizon: { selected: "11-20 Years", points: 7, note: "John is planning for a 20+ year retirement..." },
          primaryInvestmentObjective: { selected: "Growth & Income", points: 5 },
          annualSpendingPolicy: { selected: "Moderate (4-5%)", points: 5, note: "Plan to withdraw $100,000-$120,000 annually..." },
          returnExpectation: { selected: "5-7%", points: 7 },
          investmentApproach: { selected: "Willing to accept moderate fluctuations in pursuit of long-term growth, but prefers to avoid significant losses", points: 7 },
          reactionToLoss: { scenario: "Portfolio losing 15% in first year of retirement", selected: "Stay the course if fundamentals are sound, but would review the allocation", points: 7 },
          mostFearedEvent: { selected: "Prolonged market downturn in early retirement (sequence of returns risk)", points: 5 },
          investmentKnowledge: { selected: "High - Extensive investment experience, follows markets closely", points: 12 },
        },
        riskAssessment: { totalScore: 55, riskProfile: "Moderate", scoreRange: "52-67", description: "Portfolios with a Moderate objective are designed to balance growth and income..." },
        suggestedAssetAllocation: { equity: 55, fixedIncome: 35, alternatives: 8, realAssets: 8, cash: 2 },
        investmentConstraints: { esgPreference: false, notes: ["John Smith prioritizes tax efficiency...", "Inflation protection is important...", "Client prefers low-cost index funds and ETFs..."] },
      },
      null,
      2,
    ),
    "",
    "(The example above is illustrative. Extract the actual values from the PDF.)",
    "",
    "Target JSON template (fill every field):",
    JSON.stringify(RTQ_TEMPLATE, null, 2),
  ].join("\n")
}

/* ================================================================== */
/*  Estate Planning Worksheet                                         */
/*  Penobscot Financial Advisors template (9 pages, 7 sections)       */
/* ================================================================== */

export function estateExtractionPrompt(clientName: string) {
  return [
    `Extract the ${clientName} Estate Planning Worksheet into the JSON template below.`,
    "",
    "=== DOCUMENT STRUCTURE (every estate doc follows this exact layout) ===",
    "",
    "SECTION 1 — Client Information (page 3)",
    "",
    "  1A. Personal Information table (columns: Field | Details):",
    "    Full Name, Date of Worksheet, U.S. Citizen, State of Legal Residence, Primary Advisor, Advisor Phone, RTQ Source",
    "    -> personalInformation.name = Full Name value",
    "    -> personalInformation.stateOfResidence = State of Legal Residence value",
    "",
    "  1B. Marital Status table (columns: Field | Details):",
    "    Marital Status, Spouse's Full Name (with age and occupation in parentheses)",
    "    -> personalInformation.maritalStatus = Marital Status value (e.g. \"Married\")",
    "    -> personalInformation.spouse.name = spouse full name (e.g. \"Sarah Smith\")",
    "    -> personalInformation.spouse.age = spouse age as number (e.g. 63)",
    "",
    "  1C. Children & Grandchildren table (columns: Name | Age | Relationship):",
    "    Rows for children (Daughter/Son) and grandchildren (Grandchild).",
    "    -> personalInformation.children[] = objects for rows where Relationship is Daughter or Son: { name, age, relationship }",
    "    -> personalInformation.grandchildren[] = objects for rows where Relationship starts with \"Grandchild\": { name, age }",
    "    Note below table may mention 529 plans — capture this context but do not create separate fields.",
    "",
    "  Client age: The IPS mentions the client's age or retirement timeline. If the estate doc states age explicitly, use it. Otherwise infer from retirement timeline if available. If neither, use 0.",
    "    -> personalInformation.age = client age as number",
    "",
    "SECTION 2 — Estate & Bequests (pages 3-4)",
    "",
    "  2D. Value of Estate — THIS IS THE MOST CRITICAL TABLE IN THE DOCUMENT.",
    "    Contains a table with columns: Account | Account Type | Institution | Approximate Value",
    "    EVERY row in this table MUST become an entry in assetsAndRecipients[].",
    "    The table typically contains 6+ rows:",
    "      - TIAA Traditional 403(b)       Tax-Deferred    TIAA       $1,200,000",
    "      - TIAA Roth 403(b)              Tax-Free        TIAA       $350,000",
    "      - Joint Brokerage               Taxable         Vanguard   $650,000",
    "      - Vanguard Rollover IRA         Tax-Deferred    Vanguard   $300,000",
    "      - 529 College Savings Plans     Non-Qualified   Vanguard   $80,000",
    "      - Primary Residence (est.)      Non-Qualified   --         $650,000",
    "      - TOTAL row (skip this row)",
    "",
    "    For EACH row (except TOTAL):",
    "      asset = Account column text",
    "      value = Approximate Value as PLAIN NUMBER. \"$1,200,000\" -> 1200000. \"$650,000\" -> 650000. \"$80,000\" -> 80000.",
    "             NEVER return 0 for a row that has a dollar amount in the PDF.",
    "      recipient = the primary beneficiary from Section 3H table for that account (e.g. \"Sarah Smith (100%)\")",
    "      status = the \"Passes via Will?\" column from Section 3H (e.g. \"beneficiary designation\", \"Joint - passes by survivorship\", \"via will / trust\")",
    "",
    "    VALIDATION: The sum of all value fields should approximately equal the TOTAL in the last row of the table.",
    "    If you produce a 0 for any asset that has a dollar amount in the PDF, your output is WRONG.",
    "",
    "SECTION 3 — Beneficiaries (pages 4-5)",
    "",
    "  3H. Primary Beneficiaries table (columns: Account | Primary Beneficiary | Secondary Beneficiaries | Passes via Will?)",
    "    -> beneficiaries.primary[] = unique primary beneficiaries with their percentage and list of account names",
    "    -> beneficiaries.secondary[] = from Section 3I table (columns: Name | Percentage | Applicable Accounts)",
    "    -> beneficiaries.qualified = descriptive note about beneficiary designation status (e.g. \"All retirement accounts have designated primary and secondary beneficiaries on file.\")",
    "",
    "  3I. Secondary Beneficiaries table (columns: Name | Percentage | Applicable Accounts):",
    "    -> beneficiaries.secondary[] = one object per row: { name, percentage (as number, 50 not 0.5), accounts: [list of account strings] }",
    "",
    "SECTION 4 — Trusts, Executor & Guardian (page 5)",
    "",
    "  4J. Trusts table (columns: Trust Type | Status | Details):",
    "    -> trusts.revocableLivingTrust.status = Status column for \"Revocable Living Trust\" row (e.g. \"Established (2023-06-15)\")",
    "    -> trusts.revocableLivingTrust.established = extract the date from the status (e.g. \"2023-06-15\")",
    "    -> trusts.revocableLivingTrust.trustees = array of trustee names from the Details column",
    "    -> trusts.revocableLivingTrust.successorTrustee = successor trustee name from Details",
    "    -> trusts.revocableLivingTrust.beneficiaries = beneficiaries description from Details",
    "    -> trusts.revocableLivingTrust.purpose = trust purpose from the Note below the table",
    "    -> trusts.revocableLivingTrust.assets = assets description from Details",
    "    -> trusts.creditShelterTrust.status = Status for \"Credit Shelter Trust\" row (e.g. \"Not Established\")",
    "",
    "  4K. Personal Representative (Executor) table (columns: Role | Name | Relationship | Phone | City, State):",
    "    -> Look for \"Primary Executor\" and \"Alternate Executor\" rows",
    "    -> Map executor info into the actionItems or trusteeDuties as appropriate",
    "    -> trusteeDuties[] = any trustee/executor duties mentioned",
    "",
    "SECTION 5 — Advance Medical Directive / Living Will (page 6)",
    "",
    "  5A. Health Care Agent table (columns: Role | Name | Relationship | Phone | Address):",
    "    -> healthcareDirective.healthcareProxy = Primary Agent name",
    "    -> healthcareDirective.alternate = Alternate Agent name",
    "    -> healthcareDirective.document = status from Section 5B table (e.g. \"Living Will Executed (2023)\")",
    "",
    "  5B. Advance Medical Directive table (columns: Item | Status):",
    "    -> Use the Living Will row status for healthcareDirective.document",
    "",
    "SECTION 6 — Durable Power of Attorney (Financial) (page 6)",
    "",
    "  POA table (columns: Role | Name | Relationship | Document):",
    "    -> powerOfAttorney.primary = Primary Agent name",
    "    -> powerOfAttorney.alternate = Alternate Agent name",
    "    -> powerOfAttorney.document = Document column text (e.g. \"Durable POA executed 2023\")",
    "",
    "SECTION 7 — Estate Plan Summary & Financial Profile (pages 7-8)",
    "",
    "  Documents to be Prepared table (columns: Document | Priority | Notes):",
    "    -> documentsNeeded[] = one object per row: { document: \"...\", priority: \"High\"/\"Medium\"/\"Low\", status: Notes column text }",
    "",
    "  Action Items Before Attorney Appointment table (columns: # | Action Item | Responsible Party | Status):",
    "    -> actionItems[] = one object per row: { id: the # number, action: Action Item text, responsible: Responsible Party text, status: Status text }",
    "",
    "  Life Insurance: Look for bullet points in the Key Financial & Tax Considerations section mentioning insurance.",
    "    -> lifeInsurance[] = one object per policy: { type, carrier, faceValue (as number), beneficiary, purpose, note }",
    "",
    "  Charitable Giving: Look for mentions of charitable intent, DAF, specific bequests in Sections 2F and 7.",
    "    -> charitableGiving.intent = description of charitable plans",
    "    -> charitableGiving.donorAdvisedFund.status = \"Under consideration\" or \"Established\" etc.",
    "    -> charitableGiving.donorAdvisedFund.note = details about the DAF",
    "    -> charitableGiving.plannedGifts[] = array of { organization, type, amount }",
    "",
    "  Tax Exemption: From the Key Financial & Tax Considerations bullet points.",
    "    -> taxExemption = summary of federal/state estate tax exemption status",
    "",
    "=== EXAMPLE OUTPUT (for John Smith) ===",
    JSON.stringify(
      {
        personalInformation: {
          name: "John Smith",
          age: 62,
          maritalStatus: "Married",
          spouse: { name: "Sarah Smith", age: 63 },
          children: [
            { name: "Emily Smith", age: 35, relationship: "Daughter" },
            { name: "Michael Smith", age: 32, relationship: "Son" },
          ],
          grandchildren: [
            { name: "Olivia Smith", age: 8 },
            { name: "Ethan Smith", age: 5 },
          ],
          stateOfResidence: "Pennsylvania (planning to relocate to Maine upon retirement)",
        },
        assetsAndRecipients: [
          { asset: "John Smith - TIAA Traditional 403(b)", value: 1200000, recipient: "Sarah Smith (100%)", status: "beneficiary designation" },
          { asset: "John Smith - TIAA Roth 403(b)", value: 350000, recipient: "Sarah Smith (100%)", status: "beneficiary designation" },
          { asset: "John & Sarah Smith Joint Brokerage", value: 650000, recipient: "Sarah Smith (JTWROS)", status: "Joint - passes by survivorship" },
          { asset: "John Smith - Vanguard Rollover IRA", value: 300000, recipient: "Sarah Smith (100%)", status: "beneficiary designation" },
          { asset: "529 College Savings Plans (grandchildren)", value: 80000, recipient: "Olivia Smith / Ethan Smith", status: "account beneficiary" },
          { asset: "Primary Residence (est.)", value: 650000, recipient: "Joint with Sarah Smith", status: "via will / trust" },
        ],
        powerOfAttorney: { primary: "Sarah Smith", alternate: "Emily Smith", document: "Durable POA executed 2023" },
        healthcareDirective: { healthcareProxy: "Sarah Smith", alternate: "Emily Smith", document: "Living Will Executed (2023)" },
        beneficiaries: {
          qualified: "All retirement accounts have designated primary and secondary beneficiaries on file.",
          primary: [{ name: "Sarah Smith", percentage: 100, accounts: ["TIAA Traditional 403(b)", "TIAA Roth 403(b)", "Vanguard Rollover IRA"] }],
          secondary: [
            { name: "Emily Smith", percentage: 50, accounts: ["TIAA 403(b)", "Roth 403(b)", "Rollover IRA"] },
            { name: "Michael Smith", percentage: 50, accounts: ["TIAA 403(b)", "Roth 403(b)", "Rollover IRA"] },
          ],
        },
        documentsNeeded: [
          { document: "Revocable Living Trust", priority: "High", status: "Established 2023 - asset titling in progress" },
          { document: "Last Will and Testament", priority: "High", status: "Executed" },
        ],
        actionItems: [
          { id: 1, action: "Transfer primary residence and joint brokerage to Revocable Living Trust", responsible: "John + Sarah + Estate Attorney", status: "In Progress" },
          { id: 2, action: "Review and update beneficiary designations after relocation to Maine", responsible: "John + Financial Advisor", status: "Scheduled" },
        ],
        lifeInsurance: [
          { type: "Term", carrier: "TIAA-CREF Life", faceValue: 500000, beneficiary: "Sarah Smith", purpose: "Income replacement", note: "Expires at age 70" },
        ],
      },
      null,
      2,
    ),
    "",
    "(The example above is illustrative. Extract the actual values from the PDF.)",
    "REMINDER: Every row in the Section 2D Value of Estate table MUST appear in assetsAndRecipients with its correct dollar value as a number. A value of 0 for any row that has a dollar amount is WRONG.",
    "",
    "Target JSON template (fill every field):",
    JSON.stringify(ESTATE_TEMPLATE, null, 2),
  ].join("\n")
}

/* ================================================================== */
/*  Derived Insights — cross-document analysis                        */
/* ================================================================== */

export function derivedInsightsSystemPrompt() {
  return [
    "You are a senior wealth-advisor operations assistant at Penobscot Financial Advisors / TIAA Wealth Management.",
    "You receive extracted JSON from three documents for a single client: an Investment Policy Statement (IPS), a Risk Tolerance Questionnaire (RTQ), and an Estate Planning Worksheet.",
    "Your job is to produce grounded, advisor-ready insights by cross-referencing all three documents.",
    "",
    "Return JSON only with exactly three top-level keys: alerts, aiSuggestions, meetingTopics.",
    "",
    "=== OUTPUT SCHEMA ===",
    "",
    "alerts (array, 2-5 items):",
    "  Each object MUST have exactly: { type, title, description, priority }",
    "  type: one of \"warning\", \"info\", \"action\", \"success\"",
    "  priority: one of \"high\", \"medium\", \"low\"",
    "  Focus on: mismatches between IPS and RTQ, missing beneficiary designations, portfolio drift beyond allowable ranges, upcoming deadlines (RMDs, retirement), incomplete estate documents.",
    "",
    "aiSuggestions (array, 4-8 items):",
    "  Each object MUST have exactly: { priority, action, rationale, category }",
    "  priority: one of \"high\", \"medium\", \"low\"",
    "  action: a specific, concrete action the advisor should take (not vague advice)",
    "  rationale: 1-2 sentences explaining WHY, grounded in the extracted data with specific numbers",
    "  category: one of \"tax\", \"allocation\", \"estate\", \"retirement\", \"risk\", \"insurance\", \"charitable\"",
    "",
    "meetingTopics (array of strings, 5-10 items):",
    "  Short discussion topic strings suitable for a client meeting agenda.",
    "",
    "=== CROSS-REFERENCE CHECKS TO PERFORM ===",
    "",
    "1. IPS vs RTQ Alignment:",
    "   - Compare IPS riskTolerance with RTQ riskAssessment.riskProfile",
    "   - Compare IPS targetAssetAllocation percentages with RTQ suggestedAssetAllocation percentages",
    "   - Compare IPS returnGoal with RTQ returnExpectation",
    "   - Compare IPS timeHorizon with RTQ timeHorizon",
    "   - Flag any mismatches as alerts",
    "",
    "2. Estate Completeness:",
    "   - Check if every account in IPS clientProfile.accounts has a corresponding entry in estate assetsAndRecipients",
    "   - Check if beneficiary designations are complete (no missing recipients)",
    "   - Check if key estate documents are executed vs pending in documentsNeeded",
    "   - Flag incomplete trust titling, missing POA updates, pending action items",
    "",
    "3. Tax & Retirement Planning:",
    "   - Check for Roth conversion opportunity window (between retirement and RMD age)",
    "   - Check for tax-loss harvesting opportunities in taxable accounts",
    "   - Check if RMD projections align with the withdrawal policy",
    "   - Flag life insurance review needs post-retirement",
    "",
    "4. Portfolio Drift:",
    "   - If estate doc mentions current allocations (e.g. 58/32 vs 55/35 target), flag rebalancing needed",
    "",
    "=== EXAMPLE OUTPUT ===",
    JSON.stringify(
      {
        alerts: [
          { type: "warning", title: "Portfolio Drift Detected", description: "Current equity allocation (58%) exceeds IPS target (55%) and is approaching the upper allowable range of 65%. Rebalancing recommended in tax-advantaged accounts.", priority: "medium" },
          { type: "action", title: "Asset Retitling Incomplete", description: "Primary residence ($650,000) and joint brokerage ($650,000) have not yet been transferred to the Revocable Living Trust established in 2023.", priority: "high" },
        ],
        aiSuggestions: [
          { priority: "high", action: "Initiate Roth conversion ladder strategy for ages 65-72", rationale: "TIAA Traditional 403(b) holds $1,200,000 in tax-deferred assets. Converting during the 3-year window before RMDs begin at age 73 could save significant taxes on the projected $70,000/year RMDs.", category: "tax" },
          { priority: "medium", action: "Execute tax-loss harvesting in joint brokerage account before year-end", rationale: "Joint brokerage account has approximately $30,000 in unrealized losses from the 2022 market downturn. Harvesting these losses offsets future capital gains.", category: "tax" },
          { priority: "medium", action: "Establish Donor Advised Fund with $50,000 of appreciated securities", rationale: "Client intends a $50,000 legacy bequest to University Alumni Foundation. Funding a DAF with appreciated securities provides an immediate tax deduction while fulfilling the charitable goal.", category: "charitable" },
          { priority: "low", action: "Review term life insurance need post-retirement", rationale: "Term policy ($500,000, TIAA-CREF Life) expires at age 70. With combined pension income of $135,000/year and $2.5M portfolio, the need for life insurance coverage diminishes.", category: "insurance" },
        ],
        meetingTopics: [
          "Roth conversion strategy timeline and annual conversion amounts (ages 65-72)",
          "Tax-loss harvesting plan for joint brokerage account",
          "Status of primary residence and joint brokerage retitling to Revocable Living Trust",
          "Post-retirement income plan: $135,000 pension/SS + $100,000-$120,000 portfolio withdrawals",
          "Review beneficiary designations after relocation to Maine",
        ],
      },
      null,
      2,
    ),
    "",
    "(The example above is illustrative. Base your output on the actual extracted data provided.)",
  ].join("\n")
}

export function derivedInsightsPrompt(input: {
  clientName: string
  clientKey: string
  currentClient: unknown
  ipsData: unknown
  rtqData: unknown
  estateData: unknown
}) {
  return [
    `Create derived advisor insights for client ${input.clientName} (${input.clientKey}).`,
    "",
    "Analyze the three extracted documents below and produce alerts, aiSuggestions, and meetingTopics.",
    "",
    "Requirements:",
    "- alerts: 2 to 5 concise dashboard alerts. Each MUST have { type, title, description, priority }.",
    "- aiSuggestions: 4 to 8 concrete action recommendations. Each MUST have { priority, action, rationale, category }.",
    "  Valid categories: \"tax\", \"allocation\", \"estate\", \"retirement\", \"risk\", \"insurance\", \"charitable\".",
    "  Valid priorities: \"high\", \"medium\", \"low\".",
    "- meetingTopics: 5 to 10 short discussion topics as plain strings.",
    "",
    "Cross-reference checks to perform:",
    "- Compare IPS risk tolerance and asset allocation targets with RTQ results. Flag mismatches.",
    "- Verify every IPS account appears in the estate assetsAndRecipients with correct values.",
    "- Identify pending estate action items and incomplete document statuses.",
    "- Flag tax planning opportunities (Roth conversions, tax-loss harvesting, RMD planning).",
    "- Note any portfolio drift relative to target allocation ranges.",
    "- Assess insurance coverage adequacy relative to retirement income sources.",
    "",
    "Keep every description and rationale grounded in specific numbers from the extracted data.",
    "Do not mention data that is not present in the provided JSON.",
    "",
    "Client metadata:",
    JSON.stringify(input.currentClient, null, 2),
    "",
    "IPS JSON:",
    JSON.stringify(input.ipsData, null, 2),
    "",
    "RTQ JSON:",
    JSON.stringify(input.rtqData, null, 2),
    "",
    "Estate JSON:",
    JSON.stringify(input.estateData, null, 2),
  ].join("\n")
}
