import type { MockClientNonPdfData } from "../types"

export const carinaNonPdfData: MockClientNonPdfData = {
  clientKey: "carina",
  client: {
    id: "carina-voss",
    name: "Carina Voss",
    email: "carina.voss@email.com",
    phone: "(207) 555-0123",
    advisor: "Penobscot Financial Advisors",
    status: "active",
    lastMeeting: "2025-02-15",
    nextMeeting: "2025-04-20",
    documents: [
      {
        id: "ips-001",
        name: "Investment Policy Statement",
        type: "IPS",
        uploadedAt: "2024-03-15",
        status: "processed",
        pdfPath: "/documents/Carina_IPS.pdf",
      },
      {
        id: "rtq-001",
        name: "Risk Tolerance Questionnaire",
        type: "RTQ",
        uploadedAt: "2024-03-10",
        status: "processed",
        pdfPath: "/documents/Carina_RTQ.pdf",
      },
      {
        id: "estate-001",
        name: "Estate Planning Worksheet",
        type: "Estate",
        uploadedAt: "2024-03-20",
        status: "processed",
        pdfPath: "/documents/Carina_Estate.pdf",
      },
    ],
  },
  sourceDocuments: {
    ips: {
      type: "IPS",
      fileName: "Carina_IPS.pdf",
      s3Key: "carina/Carina_IPS.pdf",
      promptSlug: "ips",
      localPdfPath: "/documents/Carina_IPS.pdf",
    },
    rtq: {
      type: "RTQ",
      fileName: "Carina_RTQ.pdf",
      s3Key: "carina/Carina_RTQ.pdf",
      promptSlug: "rtq",
      localPdfPath: "/documents/Carina_RTQ.pdf",
    },
    estate: {
      type: "Estate",
      fileName: "Carina_Estate_Planning.pdf",
      s3Key: "carina/Carina_Estate_Planning.pdf",
      promptSlug: "estate",
      localPdfPath: "/documents/Carina_Estate.pdf",
      notes: "Local preview file still uses the older Carina_Estate.pdf name.",
    },
    trust: {
      type: "Trust",
      fileName: "Carina_Trust.pdf",
      s3Key: "carina/Carina_Trust.pdf",
      promptSlug: "trust",
    },
  },
  ipsSupplement: {
    currentHoldings: {
      asOf: "2026-03-15",
      currency: "USD",
      accounts: [
        {
          accountName: "Carina – Fidelity Traditional IRA",
          accountType: "Tax-Deferred",
          institution: "Fidelity",
          holdings: [
            {
              id: "carina-ira-trad-ivv",
              name: "iShares Core S&P 500 ETF",
              ticker: "IVV",
              market: "US",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              units: 615,
              price: 374,
              marketValue: 230000,
              expenseRatio: 0.0003,
            },
            {
              id: "carina-ira-trad-esgu",
              name: "iShares ESG Aware MSCI USA ETF",
              ticker: "ESGU",
              market: "US",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              units: 640,
              price: 109.38,
              marketValue: 70000,
              expenseRatio: 0.0015,
              notes: "ESG tilt per stated preference",
            },
            {
              id: "carina-ira-trad-vxus",
              name: "Vanguard Total International Stock ETF",
              ticker: "VXUS",
              market: "International",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              units: 1550,
              price: 48.39,
              marketValue: 75000,
              expenseRatio: 0.0007,
            },
            {
              id: "carina-ira-trad-agg",
              name: "iShares Core U.S. Aggregate Bond ETF",
              ticker: "AGG",
              market: "US",
              assetClass: "Fixed Income",
              instrumentType: "ETF",
              currency: "USD",
              units: 620,
              price: 96.77,
              marketValue: 60000,
              expenseRatio: 0.0003,
              durationYears: 6.2,
              creditQuality: "IG blend",
            },
            {
              id: "carina-ira-trad-tip",
              name: "iShares TIPS Bond ETF",
              ticker: "TIP",
              market: "US",
              assetClass: "Fixed Income",
              instrumentType: "ETF",
              currency: "USD",
              units: 360,
              price: 97.22,
              marketValue: 35000,
              expenseRatio: 0.0019,
              durationYears: 7.1,
            },
            {
              id: "carina-ira-trad-spaxx",
              name: "Fidelity Government Money Market",
              ticker: "SPAXX",
              market: "US",
              assetClass: "Cash & Equivalents",
              instrumentType: "Money Market",
              currency: "USD",
              marketValue: 10000,
              yield: 0.048,
            },
          ],
        },
        {
          accountName: "Carina – Fidelity ROTH IRA",
          accountType: "Tax-Free",
          institution: "Fidelity",
          holdings: [
            {
              id: "carina-ira-roth-qqq",
              name: "Invesco QQQ Trust",
              ticker: "QQQ",
              market: "US",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              units: 140,
              price: 428.57,
              marketValue: 60000,
              expenseRatio: 0.002,
            },
            {
              id: "carina-ira-roth-usmv",
              name: "iShares MSCI USA Min Vol Factor ETF",
              ticker: "USMV",
              market: "US",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              units: 420,
              price: 107.14,
              marketValue: 45000,
              expenseRatio: 0.0015,
            },
            {
              id: "carina-ira-roth-esgd",
              name: "iShares ESG Aware MSCI EAFE ETF",
              ticker: "ESGD",
              market: "International",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              units: 760,
              price: 46.05,
              marketValue: 35000,
              expenseRatio: 0.002,
              notes: "ESG tilt for developed ex-US",
            },
            {
              id: "carina-ira-roth-vnq",
              name: "Vanguard Real Estate ETF",
              ticker: "VNQ",
              market: "US",
              assetClass: "Alternatives",
              instrumentType: "REIT",
              currency: "USD",
              units: 320,
              price: 109.38,
              marketValue: 35000,
              expenseRatio: 0.0012,
            },
            {
              id: "carina-ira-roth-igf",
              name: "iShares Global Infrastructure ETF",
              ticker: "IGF",
              market: "Global",
              assetClass: "Alternatives",
              instrumentType: "ETF",
              currency: "USD",
              units: 270,
              price: 96.3,
              marketValue: 26000,
              expenseRatio: 0.004,
            },
            {
              id: "carina-ira-roth-bnd",
              name: "Vanguard Total Bond Market ETF",
              ticker: "BND",
              market: "US",
              assetClass: "Fixed Income",
              instrumentType: "ETF",
              currency: "USD",
              units: 155,
              price: 96.77,
              marketValue: 15000,
              expenseRatio: 0.0003,
              durationYears: 6,
            },
            {
              id: "carina-ira-roth-spaxx",
              name: "Fidelity Government Money Market",
              ticker: "SPAXX",
              market: "US",
              assetClass: "Cash & Equivalents",
              instrumentType: "Money Market",
              currency: "USD",
              marketValue: 4000,
              yield: 0.048,
            },
          ],
        },
        {
          accountName: "Carina – Individual Brokerage",
          accountType: "Taxable",
          institution: "Fidelity",
          holdings: [
            {
              id: "carina-broker-acme",
              name: "Acme Technologies (Employer Stock)",
              ticker: "ACME",
              market: "US",
              assetClass: "Equity",
              instrumentType: "Stock",
              currency: "USD",
              units: 820,
              price: 103.66,
              marketValue: 85000,
              costBasis: 42000,
              unrealizedGain: 43000,
              notes: "Concentrated position; diversification plan in advisor notes",
            },
            {
              id: "carina-broker-vti",
              name: "Vanguard Total Stock Market ETF",
              ticker: "VTI",
              market: "US",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              units: 880,
              price: 232.95,
              marketValue: 205000,
              expenseRatio: 0.0003,
            },
            {
              id: "carina-broker-vxus",
              name: "Vanguard Total International Stock ETF",
              ticker: "VXUS",
              market: "International",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              units: 1860,
              price: 48.39,
              marketValue: 90000,
              expenseRatio: 0.0007,
            },
            {
              id: "carina-broker-agg",
              name: "iShares Core U.S. Aggregate Bond ETF",
              ticker: "AGG",
              market: "US",
              assetClass: "Fixed Income",
              instrumentType: "ETF",
              currency: "USD",
              units: 724,
              price: 96.69,
              marketValue: 70000,
              expenseRatio: 0.0003,
              durationYears: 6.2,
              creditQuality: "IG blend",
            },
            {
              id: "carina-broker-iau",
              name: "iShares Gold Trust",
              ticker: "IAU",
              market: "Global",
              assetClass: "Alternatives",
              instrumentType: "Commodity Fund",
              currency: "USD",
              units: 1600,
              price: 25,
              marketValue: 40000,
              expenseRatio: 0.0025,
            },
            {
              id: "carina-broker-cash",
              name: "Brokerage Cash (Settlement)",
              market: "US",
              assetClass: "Cash & Equivalents",
              instrumentType: "Money Market",
              currency: "USD",
              marketValue: 10000,
              yield: 0.046,
            },
          ],
        },
      ],
    },
  },
}
