import type { MockClientNonPdfData } from "../types"

export const johnNonPdfData: MockClientNonPdfData = {
  clientKey: "john",
  client: {
    id: "john-smith",
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "(207) 555-0456",
    advisor: "Penobscot Financial Advisors",
    status: "active",
    lastMeeting: "2025-03-01",
    nextMeeting: "2025-05-15",
    documents: [
      {
        id: "ips-002",
        name: "Investment Policy Statement",
        type: "IPS",
        uploadedAt: "2024-01-20",
        status: "processed",
        pdfPath: "/documents/JohnSmith_IPS.pdf",
      },
      {
        id: "rtq-002",
        name: "TIAA Risk Tolerance Assessment",
        type: "RTQ",
        uploadedAt: "2024-01-15",
        status: "processed",
        pdfPath: "/documents/JohnSmith_RTQ.pdf",
      },
      {
        id: "estate-002",
        name: "Estate Planning Documents",
        type: "Estate",
        uploadedAt: "2023-06-20",
        status: "processed",
        pdfPath: "/documents/JohnSmith_Estate.pdf",
      },
      {
        id: "tax-001",
        name: "2024 Tax Planning Memo",
        type: "Tax",
        uploadedAt: "2025-02-01",
        status: "processed",
        pdfPath: "/documents/JohnSmith_Tax_2024.pdf",
      },
    ],
  },
  sourceDocuments: {
    ips: {
      type: "IPS",
      fileName: "JohnSmith_IPS.pdf",
      s3Key: "john/JohnSmith_IPS.pdf",
      promptSlug: "ips",
    },
    rtq: {
      type: "RTQ",
      fileName: "JohnSmith_RTQ.pdf",
      s3Key: "john/JohnSmith_RTQ.pdf",
      promptSlug: "rtq",
    },
    estate: {
      type: "Estate",
      fileName: "JohnSmith_Estate_Planning.pdf",
      s3Key: "john/JohnSmith_Estate_Planning.pdf",
      promptSlug: "estate",
    },
    tax: {
      type: "Tax",
      fileName: "JohnSmith_Tax_2024.pdf",
      s3Key: "john/JohnSmith_Tax_2024.pdf",
      promptSlug: "tax",
      notes: "Included for metadata only; the current UI does not seed a tax.json artifact.",
    },
  },
  ipsSupplement: {
    currentHoldings: {
      asOf: "2026-03-15",
      currency: "USD",
      accounts: [
        {
          accountName: "John Smith – TIAA Traditional 403(b)",
          accountType: "Tax-Deferred",
          institution: "TIAA",
          holdings: [
            {
              id: "john-403b-trad-cref-stock",
              name: "CREF Stock Account (R3)",
              market: "Global",
              assetClass: "Equity",
              instrumentType: "Mutual Fund",
              currency: "USD",
              marketValue: 350000,
              expenseRatio: 0.0032,
            },
            {
              id: "john-403b-trad-cref-global",
              name: "CREF Global Equities Account",
              market: "Global",
              assetClass: "Equity",
              instrumentType: "Mutual Fund",
              currency: "USD",
              marketValue: 200000,
              expenseRatio: 0.0038,
            },
            {
              id: "john-403b-trad-tiaa-trad",
              name: "TIAA Traditional",
              market: "US",
              assetClass: "Fixed Income",
              instrumentType: "Bond",
              currency: "USD",
              marketValue: 260000,
              yield: 0.041,
              creditQuality: "High-quality/stable value",
            },
            {
              id: "john-403b-trad-bond-index",
              name: "Vanguard Total Bond Market Index (Institutional)",
              market: "US",
              assetClass: "Fixed Income",
              instrumentType: "Mutual Fund",
              currency: "USD",
              marketValue: 160000,
              expenseRatio: 0.0004,
              durationYears: 6.1,
              creditQuality: "IG blend",
            },
            {
              id: "john-403b-trad-st-bond",
              name: "Vanguard Short-Term Bond Index",
              market: "US",
              assetClass: "Fixed Income",
              instrumentType: "Mutual Fund",
              currency: "USD",
              marketValue: 80000,
              expenseRatio: 0.0005,
              durationYears: 2.7,
              creditQuality: "IG",
            },
            {
              id: "john-403b-trad-tiaa-real-estate",
              name: "TIAA Real Estate Account",
              market: "US",
              assetClass: "Real Assets",
              instrumentType: "Private Fund",
              currency: "USD",
              marketValue: 130000,
              notes: "Direct real estate exposure (illiquid) within plan",
            },
            {
              id: "john-403b-trad-mm",
              name: "TIAA Money Market",
              market: "US",
              assetClass: "Cash & Equivalents",
              instrumentType: "Money Market",
              currency: "USD",
              marketValue: 20000,
              yield: 0.047,
            },
          ],
        },
        {
          accountName: "John Smith – TIAA Roth 403(b)",
          accountType: "Tax-Free",
          institution: "TIAA",
          holdings: [
            {
              id: "john-403b-roth-us-equity",
              name: "Vanguard Total Stock Market Index",
              market: "US",
              assetClass: "Equity",
              instrumentType: "Mutual Fund",
              currency: "USD",
              marketValue: 180000,
              expenseRatio: 0.0004,
            },
            {
              id: "john-403b-roth-intl-equity",
              name: "Vanguard Total International Stock Index",
              market: "International",
              assetClass: "Equity",
              instrumentType: "Mutual Fund",
              currency: "USD",
              marketValue: 90000,
              expenseRatio: 0.0007,
            },
            {
              id: "john-403b-roth-dividend",
              name: "Schwab U.S. Dividend Equity ETF",
              ticker: "SCHD",
              market: "US",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              marketValue: 40000,
              expenseRatio: 0.0006,
              yield: 0.034,
            },
            {
              id: "john-403b-roth-agg",
              name: "iShares Core U.S. Aggregate Bond ETF",
              ticker: "AGG",
              market: "US",
              assetClass: "Fixed Income",
              instrumentType: "ETF",
              currency: "USD",
              marketValue: 20000,
              expenseRatio: 0.0003,
              durationYears: 6.2,
            },
            {
              id: "john-403b-roth-infra",
              name: "iShares Global Infrastructure ETF",
              ticker: "IGF",
              market: "Global",
              assetClass: "Real Assets",
              instrumentType: "ETF",
              currency: "USD",
              marketValue: 20000,
              expenseRatio: 0.004,
            },
          ],
        },
        {
          accountName: "John & Sarah Smith Joint Brokerage",
          accountType: "Taxable",
          institution: "Vanguard",
          holdings: [
            {
              id: "john-broker-vti",
              name: "Vanguard Total Stock Market ETF",
              ticker: "VTI",
              market: "US",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              marketValue: 200000,
              expenseRatio: 0.0003,
            },
            {
              id: "john-broker-vxus",
              name: "Vanguard Total International Stock ETF",
              ticker: "VXUS",
              market: "International",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              marketValue: 130000,
              expenseRatio: 0.0007,
            },
            {
              id: "john-broker-schd",
              name: "Schwab U.S. Dividend Equity ETF",
              ticker: "SCHD",
              market: "US",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              marketValue: 90000,
              expenseRatio: 0.0006,
              yield: 0.034,
            },
            {
              id: "john-broker-vteb",
              name: "Vanguard Tax-Exempt Bond ETF",
              ticker: "VTEB",
              market: "US",
              assetClass: "Fixed Income",
              instrumentType: "ETF",
              currency: "USD",
              marketValue: 90000,
              expenseRatio: 0.0005,
              durationYears: 5,
            },
            {
              id: "john-broker-shv",
              name: "iShares Short Treasury Bond ETF",
              ticker: "SHV",
              market: "US",
              assetClass: "Fixed Income",
              instrumentType: "ETF",
              currency: "USD",
              marketValue: 60000,
              expenseRatio: 0.0015,
              durationYears: 0.4,
              creditQuality: "US Treasuries",
            },
            {
              id: "john-broker-vnq",
              name: "Vanguard Real Estate ETF",
              ticker: "VNQ",
              market: "US",
              assetClass: "Real Assets",
              instrumentType: "REIT",
              currency: "USD",
              marketValue: 50000,
              expenseRatio: 0.0012,
            },
            {
              id: "john-broker-cash",
              name: "Brokerage Cash (Settlement)",
              market: "US",
              assetClass: "Cash & Equivalents",
              instrumentType: "Money Market",
              currency: "USD",
              marketValue: 30000,
              yield: 0.045,
            },
          ],
        },
        {
          accountName: "John Smith – Rollover IRA",
          accountType: "Tax-Deferred",
          institution: "Vanguard",
          holdings: [
            {
              id: "john-ira-voo",
              name: "Vanguard S&P 500 ETF",
              ticker: "VOO",
              market: "US",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              marketValue: 95000,
              expenseRatio: 0.0003,
            },
            {
              id: "john-ira-bnd",
              name: "Vanguard Total Bond Market ETF",
              ticker: "BND",
              market: "US",
              assetClass: "Fixed Income",
              instrumentType: "ETF",
              currency: "USD",
              marketValue: 140000,
              expenseRatio: 0.0003,
              durationYears: 6,
            },
            {
              id: "john-ira-tip",
              name: "iShares TIPS Bond ETF",
              ticker: "TIP",
              market: "US",
              assetClass: "Fixed Income",
              instrumentType: "ETF",
              currency: "USD",
              marketValue: 65000,
              expenseRatio: 0.0019,
              durationYears: 7.1,
            },
          ],
        },
      ],
    },
    rebalancingPolicy: {
      frequency: "Quarterly review, rebalance when allocation drifts beyond allowable ranges",
      taxConsideration: "Prioritize rebalancing in tax-advantaged accounts to minimize tax impact",
    },
  },
}
