import type { MockClientNonPdfData } from "../types"

export const mariaNonPdfData: MockClientNonPdfData = {
  clientKey: "maria",
  client: {
    id: "maria-lopez",
    name: "Maria Lopez",
    email: "maria.lopez@email.com",
    phone: "(207) 555-0789",
    advisor: "Penobscot Financial Advisors",
    status: "pending",
    lastMeeting: "2025-01-10",
    nextMeeting: "2025-04-05",
    documents: [
      {
        id: "rtq-003",
        name: "Risk Tolerance Questionnaire",
        type: "RTQ",
        uploadedAt: "2025-01-10",
        status: "processing",
      },
    ],
  },
  sourceDocuments: {},
  ipsSupplement: {
    currentHoldings: {
      asOf: "2026-03-15",
      currency: "USD",
      accounts: [
        {
          accountName: "Vanguard Roth IRA",
          accountType: "Tax-Free",
          institution: "Vanguard",
          holdings: [
            {
              id: "mg-vti",
              name: "Vanguard Total Stock Market ETF",
              ticker: "VTI",
              market: "NYSE",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              units: 420,
              price: 285.5,
              marketValue: 119910,
              costBasis: 98000,
              unrealizedGain: 21910,
              yield: 1.3,
              expenseRatio: 0.03,
              durationYears: 0,
              creditQuality: "",
              notes: "Core US equity position",
            },
            {
              id: "mg-vxus",
              name: "Vanguard Total International Stock ETF",
              ticker: "VXUS",
              market: "NASDAQ",
              assetClass: "Equity",
              instrumentType: "ETF",
              currency: "USD",
              units: 950,
              price: 63.2,
              marketValue: 60040,
              costBasis: 52000,
              unrealizedGain: 8040,
              yield: 2.8,
              expenseRatio: 0.07,
              durationYears: 0,
              creditQuality: "",
              notes: "International diversification",
            },
            {
              id: "mg-bnd",
              name: "Vanguard Total Bond Market ETF",
              ticker: "BND",
              market: "NASDAQ",
              assetClass: "Fixed Income",
              instrumentType: "ETF",
              currency: "USD",
              units: 680,
              price: 72.8,
              marketValue: 49504,
              costBasis: 51000,
              unrealizedGain: -1496,
              yield: 3.5,
              expenseRatio: 0.03,
              durationYears: 6.5,
              creditQuality: "AA",
              notes: "Core bond allocation",
            },
            {
              id: "mg-vtip",
              name: "Vanguard Short-Term Inflation-Protected Securities ETF",
              ticker: "VTIP",
              market: "NASDAQ",
              assetClass: "Fixed Income",
              instrumentType: "ETF",
              currency: "USD",
              units: 600,
              price: 48.5,
              marketValue: 29100,
              costBasis: 28500,
              unrealizedGain: 600,
              yield: 4.1,
              expenseRatio: 0.04,
              durationYears: 2.5,
              creditQuality: "AAA",
              notes: "Inflation protection",
            },
            {
              id: "mg-roth-cash",
              name: "Vanguard Federal Money Market",
              ticker: "VMFXX",
              market: "",
              assetClass: "Cash & Equivalents",
              instrumentType: "Money Market",
              currency: "USD",
              units: 41446,
              price: 1.0,
              marketValue: 41446,
              costBasis: 41446,
              unrealizedGain: 0,
              yield: 4.8,
              expenseRatio: 0.11,
              durationYears: 0,
              creditQuality: "",
              notes: "Cash reserve in Roth",
            },
          ],
        },
        {
          accountName: "Fidelity 401(k)",
          accountType: "Tax-Deferred",
          institution: "Fidelity",
          holdings: [
            {
              id: "mg-fxaix",
              name: "Fidelity 500 Index Fund",
              ticker: "FXAIX",
              market: "",
              assetClass: "Equity",
              instrumentType: "Mutual Fund",
              currency: "USD",
              units: 1050,
              price: 209.0,
              marketValue: 219450,
              costBasis: 180000,
              unrealizedGain: 39450,
              yield: 1.2,
              expenseRatio: 0.015,
              durationYears: 0,
              creditQuality: "",
              notes: "S&P 500 index — employer plan core",
            },
            {
              id: "mg-fxnax",
              name: "Fidelity U.S. Bond Index Fund",
              ticker: "FXNAX",
              market: "",
              assetClass: "Fixed Income",
              instrumentType: "Mutual Fund",
              currency: "USD",
              units: 8500,
              price: 10.7,
              marketValue: 90950,
              costBasis: 93000,
              unrealizedGain: -2050,
              yield: 3.4,
              expenseRatio: 0.025,
              durationYears: 6.3,
              creditQuality: "AA",
              notes: "Core bond in 401(k)",
            },
            {
              id: "mg-fskax",
              name: "Fidelity Total Market Index Fund",
              ticker: "FSKAX",
              market: "",
              assetClass: "Equity",
              instrumentType: "Mutual Fund",
              currency: "USD",
              units: 780,
              price: 145.0,
              marketValue: 113100,
              costBasis: 95000,
              unrealizedGain: 18100,
              yield: 1.3,
              expenseRatio: 0.015,
              durationYears: 0,
              creditQuality: "",
              notes: "Broad US equity complement",
            },
            {
              id: "mg-401k-cash",
              name: "Fidelity Government Money Market",
              ticker: "SPAXX",
              market: "",
              assetClass: "Cash & Equivalents",
              instrumentType: "Money Market",
              currency: "USD",
              units: 26500,
              price: 1.0,
              marketValue: 26500,
              costBasis: 26500,
              unrealizedGain: 0,
              yield: 4.6,
              expenseRatio: 0.42,
              durationYears: 0,
              creditQuality: "",
              notes: "Cash in 401(k)",
            },
          ],
        },
      ],
    },
  },
}
